### ISSUE TITLE
Opening thread issue

### ISSUE THREAD

**Issue by AviaJae** [AkimotoRyou/ModMail#22]
When some users wanted to create a thread it will says this.

An Error Occured.

Contact bot Owner: @botowner
Error Name: TypeError
Error Message: Cannot read property 'send' of undefined

**Comment by AkimotoRyou** [comment]
Can you show what's logged in the console?

**Comment by AviaJae** [comment]
No, its not logged in the console.

**Comment by AkimotoRyou** [comment]
Most of the action the bot taken are logged in console i need to know the console logs to find in which file the bot break to help you.

**Comment by AviaJae** [comment]
ok the console says that


> Activity Updated. Index : 3
char sucks#6465(828131912589115423) called new command.
TypeError: Cannot read property 'send' of undefined
    at Object.execute (/home/runner/ModMail/functions/newFn.js:38:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Client.<anonymous> (/home/runner/ModMail/index.js:376:3)

**Comment by AkimotoRyou** [comment]
It should be because the bot can't get the log channel inside the Thread Server somehow. Please re-check the logChannelID value. ![IMG_20210601_132843.jpg](https://user-images.githubusercontent.com/39645219/120276834-68fe7680-c2dd-11eb-89f9-5b4fba0314ce.jpg)

**Comment by AviaJae** [comment]
it must be the botlogs channel id is the same as the bot channel id so wait maybe i will change it
