### ISSUE TITLE
How do I change the custom status for the bot?

### ISSUE THREAD

**Issue by ClownY-Dev** [AkimotoRyou/ModMail#28]
I made a personal bot to test the codes, but unfortunately I'm unable to find the file where I can change the bot status. Please let me know & help me with this.

**Comment by AkimotoRyou** [comment]
The status message is in `locale/en.js` search for `activity` function there. The code that change bot status itself is in `functions/updateActivity.js`.

**Comment by ClownY-Dev** [comment]
> The status message is in `locale/en.js` search for `activity` function there. The code that change bot status itself is in `functions/updateActivity.js`.

Thanks for your help, I also had one more doubt. What is ThreadServerID & Do We Need To Have A Seperate Discord Server For That?

**Comment by AkimotoRyou** [comment]
No, you can use same server for both thread and main server ID. For more information use `<prefix>config <info|i|?> <config name>` command.

**Comment by ClownY-Dev** [comment]
> No, you can use same server for both thread and main server ID. For more information use `<prefix>config <info|i|?> <config name>` command.

I have already kept the Server ID same in `config.js` & `index.js` , but I still face the same problem.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/80631366/135198734-0fd1237e-b474-474b-8881-d9353d1ddf0b.png">

**Comment by AkimotoRyou** [comment]
Any values you put in `config.json` only used for default value, so if you edit the file after bot initiation you'll need to use `reset` command to use that value. Using `set` command would be more practical and that's the reason why there's such command.And the one in `index.js` only used as a frame, any value you put there will be replaced by the one from database.

**Comment by ClownY-Dev** [comment]
> Any values you put in `config.json` only used for default value, so if you edit the file after bot initiation you'll need to use `reset` command to use that value. Using `set` command would be more practical and that's the reason why there's such command.And the one in `index.js` only used as a frame, any value you put there will be replaced by the one from database.

Done!
It is working fine now. Thanks for helping me out buddy.
