### ISSUE TITLE
What is the bot‘s prefix?

### ISSUE THREAD

**Issue by RobertPlays** [AkimotoRyou/ModMail#34]
I cannot seem to find the bot‘s prefix.

**Comment by AkimotoRyou** [comment]
It doesn't have one, it use slash command which will be deployed after you finish the setup.
https://support.discord.com/hc/en-us/articles/1500000368501-Slash-Commands-FAQ

**Comment by RobertPlays** [comment]
How do you create a thread though? I am dming the bot but nothing is happening as of now.

**Comment by AkimotoRyou** [comment]
you need to use `/create` command.

**Comment by RobertPlays** [comment]
Not working.

**Comment by RobertPlays** [comment]
Wait nevermind, but now it won't let me reply in the channel where it was created.

**Comment by AkimotoRyou** [comment]
Did you use `/reply` command? what's the error it give you?

**Comment by RobertPlays** [comment]
I did use the /reply in dms, but in the actual channel it does not show up.

**Comment by AkimotoRyou** [comment]
It's a global command  so you need to wait up to an hour for it to properly show. That's just how it work

**Comment by RobertPlays** [comment]
alr, I will just host my bot then 24/7 and go sleep since its 2 am.

**Comment by RobertPlays** [comment]
Thank you!
